name: Auto Pull Request with Merge

on:
  schedule:
    - cron: "*/5 * * * *" # Adjust the schedule as needed

jobs:
  auto_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Git User Name and Email
        run: |
          git config user.name "themuuln"
          git config user.email "zerone.offical@gmail.com"

      - name: Install hub
        run: |
          curl -L -o hub.tgz https://github.com/github/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz
          tar xvzf hub.tgz
          sudo ./hub-linux-amd64-2.14.2/install

      - name: Create Empty Pull Request
        run: |
          cd $GITHUB_WORKSPACE
          branch="main"  # Change this to the target branch

          # Generate a unique branch name
          branch_name="auto-pull-request-$(date +%s)"

          # Create a new branch
          git checkout -b $branch_name

          # Create an empty commit to trigger a pull request
          git commit --allow-empty -m "Auto Pull Request Trigger"

          # Push the new branch to the repository
          git push origin $branch_name

          # Create the pull request
          pr_url=$(hub pull-request -m "Automated Pull Request" -b $branch -h $branch_name)

          # Merge the pull request
          hub api -X PUT $pr_url/merge

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
