name: Auto Pull Request

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  auto_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Empty Pull Request
        run: |
          cd $GITHUB_WORKSPACE
          branch="main"  

          branch_name="auto-pull-request-$(date +%s)"

          git checkout -b $branch_name

          git commit --allow-empty -m "Auto Pull Request Trigger"

          git push origin $branch_name

          hub pull-request -m "Automated Pull Request" -b $branch -h $branch_name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
