name: Auto Pull Request with Merge

on:
  schedule:
    - cron: "*/5 * * * *" # Adjust the schedule as needed

jobs:
  auto_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Git User Name and Email
        run: |
          git config user.name "themuuln"  # Replace with your GitHub username
          git config user.email "zerone.offical@gmail.com"  # Replace with your GitHub email

      - name: Create Empty Pull Request
        run: |
          cd $GITHUB_WORKSPACE
          branch="main"  # Change this to the target branch

          # Generate a unique branch name
          branch_name="auto-pull-request-$(date +%s)"

          # Create a new branch
          git checkout -b $branch_name

          # Create an empty commit to trigger a pull request
          git commit --allow-empty -m "Auto Pull Request Trigger"

          # Push the new branch to the repository
          git push origin $branch_name

          # Create the pull request using your GitHub credentials
          pr_url=$(curl -X POST -u "YourGitHubUsername:$PERSONAL_ACCESS_TOKEN" -d '{
            "title": "Automated Pull Request",
            "head": "'$branch_name'",
            "base": "'$branch'"
          }' "https://api.github.com/repos/USERNAME/REPO_NAME/pulls")

          # Merge the pull request (if needed) using your GitHub credentials
          curl -X PUT -u "YourGitHubUsername:$PERSONAL_ACCESS_TOKEN" "$pr_url/merge"
        env:
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
